In [1]:
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [2]:
import tensorflow as tf

In [3]:
#To check the version of TensorFlow
print(tf.__version__)

2.16.1


In [4]:
import numpy as np
from numpy import *

# Creating tensors

In [5]:
#Creating a tensor object using tf.constant
a_constant = tf.constant([1,2,3,4,5,6])

In [6]:
a_constant

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

#### generate a similar tensor object using the tf.Variable function:

In [7]:
#Creating a tensor object using tf.Variable
a_variable = tf.Variable([1,2,3,4,5,6])

In [8]:
a_variable

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

#### Although the input in both cases is the same, tf.constant and tf.Variable are different. Tensors generated using tf.constant cannot be changed, whereas tf.Variable tensors can be reassigned in the future. 

#### another way of generating tensors using tf.range:

In [9]:
# Creating tensors using the range function
a_range = tf.range(start=1, limit=7)

In [10]:
a_range

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

#### the output of a_constant and a_range is the same and is slightly different from the output of a_variable

# Tensor rank

The rank of a tensor
identifies the number of dimensions of the tensor. A tensor
with a rank of 0 is called a scalar, as it has no dimensions. A
vector is a rank 1 tensor as it has only one dimension, while
a matrix of a two-dimension tensor has a rank of 2.
---
A classificação de um tensor identifica o número de dimensões do tensor. Um tensor com classificação 0 é chamado de escalar, pois não possui dimensões. Um vetor é um tensor de classificação 1, pois possui apenas uma dimensão, enquanto uma matriz de um tensor bidimensional possui classificação 2.

Examples of scalar quantities are time, mass,
energy, and speed; these quantities have a single numeric
value, for example, 1, 23.4, or 50.

Let us return to our
notebook and generate a scalar using the tf.constant
function:

In [11]:
# scalar
a = tf.constant(1)

In [12]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=1>

Na saída retornada, podemos ver que a forma foi nenhum valor, pois a saída é uma quantidade escalar com um único
saída numérica. Se testarmos um valor de 4, a saída numpy será 4, enquanto outras propriedades de saída permanecerão as
o mesmo, pois 4 ainda é uma quantidade escalar.

Now that we have seen what a scalar (rank 0 tensor) is, let
us go a step further by looking at a vector. For context, a
vector quantity has both magnitude and direction.

Examples of vectors are acceleration, velocity, and force.

For a change, this time, we will use
floats since we can generate tensors with floats

In [13]:
# vector
b = tf.constant([1.2,2.3,3.4,4.5])

In [14]:
b

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.2, 2.3, 3.4, 4.5], dtype=float32)>

From our result, we see the data type returned is float32
with a shape of 4.

A matrix is an array of
numbers listed in rows and columns.

In [15]:
# matrix
c = tf.constant([[1,2], [3,4]])

In [16]:
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

The preceding matrix is a 2 x 2 matrix, which we can infer
by inspecting the shape output. We see that the data type is
also int32. Let us generate a higher-dimensional tensor:

In [19]:
# 3 - dimensional tensor
d = tf.constant([[[1,2], [3,4], [5,6]], [[7,8], [9,10], [11,12]]])

In [20]:
d

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])>

The output is a 2 x 3 x 2 tensor, with a data type of int32

## Properties of tensors