In [1]:
%pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 132.2 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.9/589.9 MB 902.8 kB/s eta 0:00:0000:0100:35
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 1.3 MB/s eta 0:00:00 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 1.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 674.0 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 934.9 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 901.9 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 418.7 kB/s eta 0:00:0000:0100:02
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 443.7 kB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 1.6 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.6/294.6 kB 402.3 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [2]:
import tensorflow as tf

2024-05-05 07:45:28.639103: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-05 07:45:28.694075: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-05-05 07:45:28.944366: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-05 07:45:30.345836: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [3]:
#To check the version of TensorFlow
print(tf.__version__)

2.16.1


In [4]:
import numpy as np
from numpy import *

# Creating tensors

In [5]:
#Creating a tensor object using tf.constant
a_constant = tf.constant([1,2,3,4,5,6])

2024-05-05 07:45:31.793807: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-05-05 07:45:31.794867: W tensorflow/core/common_runtime/gpu/gpu_device.cc:2251] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [6]:
a_constant

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

#### generate a similar tensor object using the tf.Variable function:

In [7]:
#Creating a tensor object using tf.Variable
a_variable = tf.Variable([1,2,3,4,5,6])

In [8]:
a_variable

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

#### Although the input in both cases is the same, tf.constant and tf.Variable are different. Tensors generated using tf.constant cannot be changed, whereas tf.Variable tensors can be reassigned in the future. 

#### another way of generating tensors using tf.range:

In [9]:
# Creating tensors using the range function
a_range = tf.range(start=1, limit=7)

In [10]:
a_range

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

#### the output of a_constant and a_range is the same and is slightly different from the output of a_variable

# Tensor rank

The rank of a tensor
identifies the number of dimensions of the tensor. A tensor
with a rank of 0 is called a scalar, as it has no dimensions. A
vector is a rank 1 tensor as it has only one dimension, while
a matrix of a two-dimension tensor has a rank of 2.
---
A classificação de um tensor identifica o número de dimensões do tensor. Um tensor com classificação 0 é chamado de escalar, pois não possui dimensões. Um vetor é um tensor de classificação 1, pois possui apenas uma dimensão, enquanto uma matriz de um tensor bidimensional possui classificação 2.

Examples of scalar quantities are time, mass,
energy, and speed; these quantities have a single numeric
value, for example, 1, 23.4, or 50.

Let us return to our
notebook and generate a scalar using the tf.constant
function:

In [11]:
# scalar
a = tf.constant(1)

In [12]:
a

<tf.Tensor: shape=(), dtype=int32, numpy=1>

Na saída retornada, podemos ver que a forma foi nenhum valor, pois a saída é uma quantidade escalar com um único
saída numérica. Se testarmos um valor de 4, a saída numpy será 4, enquanto outras propriedades de saída permanecerão as
o mesmo, pois 4 ainda é uma quantidade escalar.

Now that we have seen what a scalar (rank 0 tensor) is, let
us go a step further by looking at a vector. For context, a
vector quantity has both magnitude and direction.

Examples of vectors are acceleration, velocity, and force.

For a change, this time, we will use
floats since we can generate tensors with floats

In [13]:
# vector
b = tf.constant([1.2,2.3,3.4,4.5])

In [14]:
b

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.2, 2.3, 3.4, 4.5], dtype=float32)>

From our result, we see the data type returned is float32
with a shape of 4.

A matrix is an array of
numbers listed in rows and columns.

In [15]:
# matrix
c = tf.constant([[1,2], [3,4]])

In [16]:
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

The preceding matrix is a 2 x 2 matrix, which we can infer
by inspecting the shape output. We see that the data type is
also int32. Let us generate a higher-dimensional tensor:

In [17]:
# 3 - dimensional tensor
d = tf.constant([[[1,2], [3,4], [5,6]], [[7,8], [9,10], [11,12]]])

In [18]:
d

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]], dtype=int32)>

The output is a 2 x 3 x 2 tensor, with a data type of int32

## Properties of tensors

We will use tf.Variable to generate a scalar tensor, selecting float16 as the data type and naming it TDC . (If you are wondering what TDC means, it is the TensorFlow Developer Certificate.)

In [19]:
# scalar
a = tf.Variable(1.1, name="TDC", dtype=float16)

In [20]:
a

<tf.Variable 'TDC:0' shape=() dtype=float16, numpy=1.1>

When we examine the output, we can see the name of the tensor is now TDC: 0, and the shape of the tensor is 0 since the tensor is of rank 0. The data type we selected was float16. And finally, the tensor has a numpy value of 1.1 also. This example shows how we can configure properties such as data type and name when constructing tensors in TensorFlow.

Next, let us look at a vector and see what information we can learn from its properties:

In [21]:
# vector 
b = tf.Variable([1.2, 2.3, 3.4, 4.5], name="Vector", dtype=float16)

In [22]:
b

<tf.Variable 'Vector:0' shape=(4,) dtype=float16, numpy=array([1.2, 2.3, 3.4, 4.5], dtype=float16)>

Here, again, we included arguments and the name of the tensor and we changed the default data type.

When we print the result of a tensor output, we can see the different properties of the
tensor, like when we examined the scalar and vector quantities. However, by leveraging TensorFlow functions,
we can gain more information about a tensor. Let us start by using the tf.rank() function to inspect the rank of a scalar, vector, and matrix:

In [23]:
# scalar
a = tf.constant(1.1)

In [24]:
a

<tf.Tensor: shape=(), dtype=float32, numpy=1.1>

In [25]:
# vector
b = tf.constant([1.2, 2.3, 3.4, 4.5])

In [26]:
b

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.2, 2.3, 3.4, 4.5], dtype=float32)>